### ISSUE TITLE
Não use lista para algo tão simples

### ISSUE THREAD

**Issue by ricardolopes86** [flamarion/myfinancesV2#1]
Aqui não tem necessidade de usar como lista, você pode usar uma string normal:
https://github.com/flamarion/myfinancesV2/blob/0774f1b9cdf68c2b3caa05df654602ed487f4be0/myfinances/account.py#L19
Não terá nenhum impacto pro seu código.

**Comment by flamarion** [comment]
Fixed. Please, remove the db_dir (rm -rf ~/.db_dir) or backup it if you want, then run the "run.py" again.
